name: 폰 켜기 테스트

on:
  workflow_dispatch:

jobs:
  open-app-job:
    runs-on: self-hosted

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Appium 라이브러리 설치
        run: |
          pip install Appium-Python-Client

      - name: 앱 실행 스크립트 가동
        run: |
          python simple_start.py
